//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda_Mainnotes
    {
        public int agendaMainID { get; set; }
        public System.DateTime Post_date { get; set; }
        public string Poster { get; set; }
        public string committee_name { get; set; }
        public string Post { get; set; }
    }
}
