//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class committee_Memberlist
    {
        public int ID { get; set; }
        public string name_ofCommittee { get; set; }
        public string Uname_ofMember { get; set; }
        public System.DateTime member_joindate { get; set; }
        public System.DateTime memeber_endate { get; set; }
        public string active { get; set; }
    }
}
