//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Committee
    {
        public int Committee_ID { get; set; }
        public string Committee_Name { get; set; }
        public System.DateTime Committee_Startdate { get; set; }
        public System.DateTime Committee_Enddate { get; set; }
        public string Committee_Active { get; set; }
        public string Committee_Faculty { get; set; }
        public Nullable<int> numberofpeople { get; set; }
    }
}
