//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_memberlist
    {
        public int courseID { get; set; }
        public string CourseName { get; set; }
        public int CourseNum { get; set; }
        public string instructor { get; set; }
        public System.DateTime add_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string active { get; set; }
    }
}
