//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursepreq
    {
        public int courseID { get; set; }
        public string courseName { get; set; }
        public int courseNumber { get; set; }
        public string course_preqforName { get; set; }
        public Nullable<int> course_preqforNumb { get; set; }
        public Nullable<int> course_preqforid { get; set; }
        public Nullable<int> course_group { get; set; }
        public int course_case { get; set; }
    
        public virtual courseslist courseslist { get; set; }
    }
}
