//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public int ID { get; set; }
        public string Recipient { get; set; }
        public string Sender { get; set; }
        public System.DateTime Senddate { get; set; }
        public string Message { get; set; }
        public byte[] attachments { get; set; }
    }
}
