//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meeting()
        {
            this.agendanotes = new HashSet<agendanote>();
        }
    
        public int ID { get; set; }
        public string committee_name { get; set; }
        public string Message_Agenda { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendanote> agendanotes { get; set; }
    }
}
